[package]
name = "rust-actix-race-condition"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
simple_logger = "5.0.0"
actix-web = "4"
dashmap = "6.0.1"
chrono = "0.4.38"
tokio = "1.39.3"
random-string = "1.1.0"
